version: "1"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
    full_str: "background"
  - id: 1
    label: "open-pack-remove-app"
    full_str: "Open inner packaging and remove applicator."
  - id: 2
    label: "insert-applicator"
    full_str: "Insert applicator into wound track as close to bleeding source as possible."
  - id: 3
    label: "insert-plunger-w-pressure"
    full_str: "Insert plunger into applicator."
  - id: 4
    label: "push-plunger"
    full_str: "Push plunger firmly to deploy sponges into wound."
  - id: 5
    label: "apply-pressure"
    full_str: "Apply manual pressure if necessary."
