version: "1"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
    full_str: "background"
  - id: 1
    label: "cover-seal-wound"
    full_str: "With gloved hand, cover and seal wound site."
  - id: 2
    label: "open-pack"
    full_str: "Open vented chest seal package."
  - id: 3
    label: "clean-wound-site"
    full_str: "Wipe blood and body fluids from wound site."
  - id: 4
    label: "peel-seal-backer"
    full_str: "Peel away chest seal backer."
  - id: 5
    label: "place-seal"
    full_str: "Place chest seal with circle of vents over wound site and seal to chest."
