version: "1"
title: "Oatmeal"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  # - full_str: Complete sentence that fully represents the label.
  # - depends: List of ids that the item depends on
  # - repeat: Optional field that indicated that the item must be repeated X times
  - id: 0
    label: "background"
  - id: 1
    label: "measure-half-cup-water"
    full_str: "Measure 1/2 cup water in the liquid measuring cup."
    depends:
  - id: 2
    label: "pour-water-bowl"
    full_str: "Pour the water from the liquid measuring cup into the microwave safe bowl."
    depends: [1]
  - id: 3
    label: "measure-1-tbsp-oats"
    full_str: "Measure 1 Tablespoon of quick-cook oats and place in a microwave-safe bowl."
    depends:
    repeat: 4
  - id: 4
    label: "microwave-30-sec"
    full_str: "Microwave for 30 seconds."
    depends: [3, 2]
  - id: 5
    label: "add-raisins"
    full_str: "Add handful of raisins"
    depends: [4]
  - id: 6
    label: "stir"
    full_str: "Stir"
    depends: [5]
  - id: 7
    label: "microwave-60-sec"
    full_str: "Microwave for 60 seconds"
    depends: [6]
  - id: 8
    label: "slice-banana"
    full_str: "Slice banana"
    depends:
  - id: 9
    label: "top-banana-slices"
    full_str: "Top with banana slices."
    depends: [8, 12]
  - id: 10
    label: "sprinkle-cinnamon"
    full_str: "sprinkle with cinnamon"
    depends: [12]
  - id: 11
    label: "drizzle-honey"
    full_str: "drizzle with honey"
    depends: [12]
  - id: 12
    label: "stir-again"
    full_str: "Stir"
    depends: [7]
  - id: 13
    label: "done"
    full_str: "done"
    depends: [9, 10, 11]
