version: "1.1"
title: "Dessert Quesadilla"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  # - full_str: Complete sentence that fully represents the label.
  # - depends: List of ids that the item depends on
  # - repeat: Optional field that indicated that the item must be repeated X times
  - id: 0
    label: "background"
    full_str: "background"
  - id: 1
    label: "place-tortilla"
    full_str: "Place tortilla on cutting board"
    depends:
  - id: 2
    label: "scoop-nutella"
    full_str: "Use the butter knife to scoop nutella from the jar"
    depends: [11]
  - id: 3
    label: "spread-nutella-tortilla"
    full_str: "Spread nutella onto tortilla, leaving Â½ inch uncovered at the edges"
    depends: [1, 2]
  - id: 4
    label: "slice-banana"
    full_str: "Slice banana"
    depends: [10]
  - id: 5
    label: "top-banana-slices"
    full_str: "Top with banana slices."
    depends: [3, 4]
  - id: 6
    label: "sprinkle-cinnamon"
    full_str: "Sprinkle small amount of cinnamon onto tortilla"
    depends: [3]
  - id: 7
    label: "fold-tortilla-half"
    full_str: "Fold tortilla in half into semi-cirlce"
    depends: [6, 5]
  - id: 8
    label: "slice-tortilla-half"
    full_str: "Slice tortilla in half using butter knife to create two triangular wedges"
    depends: [7]
  - id: 9
    label: "place-tortilla-wedge"
    full_str: "Place tortilla wedge on the plate"
    depends: [8]
    repeat: 2
  - id: 10
    label: "clean-knife"
    full_str: "Clean the knife by wiping with a paper towel."
    depends:
  - id: 11
    label: "clean-knife"
    full_str: "Clean the knife by wiping with a paper towel."
    depends:
  - id: 12
    label: "done"
    full_str: "done"
    depends: [9]
