version: "3.4"

services:

  #
  # Build requirements
  #

  workspace-base-dev:
    image: ${PTG_REGISTRY}/workspace-base-dev:${PTG_TAG}
    build:
      context: ..  # repo root
      dockerfile: docker/workspace-base-dev/Dockerfile
      cache_from:
        # In order of descending precedence
        - ${PTG_REGISTRY}/workspace-base-dev:${PTG_TAG}
        - ${PTG_REGISTRY}/workspace-base-dev:latest
    profiles:
      - build-only


  workspace-build-dev:
    image: ${PTG_REGISTRY}/workspace-build-dev:${PTG_TAG}
    depends_on:
      - workspace-base-dev
    build:
      context: ..  # repo root
      dockerfile: docker/workspace-build/Dockerfile
      args:
        BASE_IMAGE: workspace-base-dev
        ANGEL_WORKSPACE_DIR:  # from .env file
        PTG_REGISTRY:  # from .env file
        PTG_TAG:  # from .env file
      cache_from:
        # In order of descending precedence
        - ${PTG_REGISTRY}/workspace-build-dev:${PTG_TAG}
        - ${PTG_REGISTRY}/workspace-build-dev:latest
    profiles:
      - build-only

  #
  # Runnable services
  #

  workspace-shell-dev:
    # Development workspace shell, including source and build mounting.
    # Includes X11 passthrough. Requires XAUTH_FILEPATH to be defined in env.
    image: ${PTG_REGISTRY}/workspace-build-dev:${PTG_TAG}
    privileged: true
    network_mode: host
    tty: true
    volumes:
      - /dev/shm:/dev/shm
      # Host sharing
      - ../poetry.lock:${ANGEL_WORKSPACE_DIR}/poetry.lock
      - ../pyproject.toml:${ANGEL_WORKSPACE_DIR}/pyproject.toml
      - ../ros:${ANGEL_WORKSPACE_DIR}/src
      - ../tmux:${ANGEL_WORKSPACE_DIR}/tmux
      - ../angel_system:${ANGEL_WORKSPACE_DIR}/angel_system
      - ../model_files:${ANGEL_WORKSPACE_DIR}/model_files
      - ../config:${ANGEL_WORKSPACE_DIR}/config
      - ./workspace_build.sh:${ANGEL_WORKSPACE_DIR}/workspace_build.sh
      - ./workspace_entrypoint.sh:${ANGEL_WORKSPACE_DIR}/workspace_entrypoint.sh
      - ./workspace_setenv.sh:${ANGEL_WORKSPACE_DIR}/workspace_setenv.sh
      - ../ros_bags:${ANGEL_WORKSPACE_DIR}/ros_bags
      # Build environment things
      - ${WORKSPACE_SHELL_HOST_DIR}/build:${ANGEL_WORKSPACE_DIR}/build
      - ${WORKSPACE_SHELL_HOST_DIR}/install:${ANGEL_WORKSPACE_DIR}/install
      - ${WORKSPACE_SHELL_HOST_DIR}/log:${ANGEL_WORKSPACE_DIR}/log
      - ${WORKSPACE_SHELL_HOST_DIR}/stuff:${ANGEL_WORKSPACE_DIR}/stuff
      - ${WORKSPACE_SHELL_HOST_DIR}/ros_logs:/root/.ros/logs
      - ${WORKSPACE_SHELL_HOST_DIR}/cache/torch:/root/.cache/torch
      # X11 things
      - /tmp/.X11-unix:/tmp/.X11-unix
      # assume this file exists, should be created before running.
      - ${XAUTH_FILEPATH}:/tmp/.docker.xauth
    environment:
      HISTFILE: ${ANGEL_WORKSPACE_DIR}/stuff/bash_history
      CYCLONE_DDS_INTERFACE:  # from .env file or parent environment
      SETUP_WORKSPACE_INSTALL:  # from .env file or parent environment
      DISPLAY:  # pull from current environment
      XAUTHORITY: /tmp/.docker.xauth
      PYTHONDONTWRITEBYTECODE: 1  # Don't write .pyc files when in workspace

  workspace-shell-dev-gpu:
    extends:
      service: workspace-shell-dev
    # https://docs.docker.com/compose/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              driver: nvidia
              count: all
              # device_ids: ['0', '3']  # mutually exclusive with count

  workspace-shell-run:
    # Service for running ros2 commands in the context of the image's build
    # workspace.
    image: ${PTG_REGISTRY}/workspace-build-dev:${PTG_TAG}
    privileged: true
    network_mode: host
    volumes:
      - /dev/shm:/dev/shm
    environment:
      CYCLONE_DDS_INTERFACE:  # from .env file
      SETUP_WORKSPACE_INSTALL: 1  # yes, activate the workspace here
