_BASE_: "/angel_workspace/angel_system/berkeley/configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 5
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("BBN_M2_YoloModel_train",)
  TEST: ("BBN_M2_YoloModel_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
#SOLVER:
#  STEPS: (120000, 160000)
#  MAX_ITER: 180000  # 180000 * 16 / 100000 ~ 28.8 epochs
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001

OUTPUT_DIR: '/Padlock_DT/training/bbn_M1_hands_M2/resnet50'

SOLVER:
  TOTAL_IMAGE_NUMBER: 5873
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  STEPS: (34000, 41000)
  MAX_ITER: 64000 # 500 * 1 / 10 ~ 500 epochs
  CHECKPOINT_PERIOD: 1000
  EPOCH: 50

VISUALIZER:
  CAM: False


