# Schema version.
version: "1.0"

# Task title for display purposes.
title: "Multi task example"

# Layout of the steps that define this task.
tasks:
  # Item format:
  # - id: Identifying integer for the task.
  # - config_file: Path to the task config file representing this task.
  #   It is expected that these paths are relative to where this tool is run.
  #   (i.e. relative to $(ANGEL_WORKSPACE)).
  - id: 0
    label: "coffee"
    config_file: "./config/tasks/recipe_coffee.yaml"
    active: true
  - id: 1
    label: "tea"
    config_file: "./config/tasks/recipe_tea.yaml"
    active: true
  - id: 2
    label: "pinwheel"
    config_file: "./config/tasks/recipe_pinwheel.yaml"
    active: false
  - id: 3
    label: "oatmeal"
    config_file: "./config/tasks/recipe_oatmeal.yaml"
    active: false
  - id: 4
    label: "dessert_quesadilla"
    config_file: "./config/tasks/recipe_dessertquesadilla.yaml"
    active: true
