version: "1.0"
title: "Pour-over coffee"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  # - full_str: Complete sentence that fully represents the label.
  # - activity_ids: List of activity ids that correspond to the task 
  - id: 0
    label: "background"
    full_str: "background"
    activity_ids: [0]
  - id: 1
    label: "water-in-kettle"
    full_str: "Measure 12 ounces of cold water and transfer to a kettle."
    activity_ids: [9, 1, 2]
  - id: 2
    label: "place-dipper-on-mug"
    full_str: "Assemble the filter cone. Place the dripper on top of a coffee mug."
    activity_ids: [26]
  - id: 3
    label: "prepare-paper-filter"
    full_str: "Prepare the filter insert by folding the paper filter in half to create a semi-circle, and in half again
to create a quarter-circle. Place the paper filter in the dripper and spread open to create a cone."
    activity_ids: [27, 28, 29, 30]
  - id: 4
    label: "coffee-beans-to-grounds"
    full_str: "Weigh the coffee beans and grind until the coffee grounds are the consistency of coarse sand,
about 20 seconds. Transfer the grounds to the filter cone."
    activity_ids: [31, 32, 33, 34, 35, 36, 37]
  - id: 5
    label: "check-temp"
    full_str: "Check the temperature of the water."
    activity_ids: [3, 4, 5]
  - id: 6
    label: pour-water-grounds-wet"
    full_str: "Pour a small amount of water in the filter to wet the grounds. Wait about 30 seconds."
    activity_ids: [38]
  - id: 7
    label: "pour-water-grounds-circular"
    full_str: "Slowly pour the rest of the water over the grounds in a circular motion. Do not overfill beyond
the top of the paper filter."
    activity_ids: [39]
  - id: 8
    label: "drain-and-cleanup"
    full_str: "Let the coffee drain completely into the mug before removing the dripper. Discard the paper
filter and coffee grounds."
    activity_ids: [40, 41, 42, 43]
