# Schema version.
version: "1.0"

# Reference to the activity classification labels configuration that we will
# reference into.
activity_labels: "./config/activity_labels/recipe_tourniquet.yaml"

# Reference to the file defining the mean and standard deviation of the
# activity classifications to be used by the HMM. For N activities, both the
# mean and standard deviation should be N x N matrices such that when activity
# i is actually occuring, the classifier will emit confidence
# mean[i, j] +/- std[i, j] for activity j.
activity_mean_and_std_file: "./model_files/recipe_m2_apply_tourniquet.npy"

# Task title for display purposes.
title: "M2 Apply tourniquet"

# Layout of the steps that define this task.
steps:
  # Item format:
  # - id: Identifying integer for the step.
  # - activity_id: The ID of an activity classification associated with this
  #                step. This must reference an ID within the `activity_labels`
  #                configuration file referenced above.
  # - description: Human semantic description of this step.
  # - median_duration_seconds: Median expected time this task will
  #                            consume in seconds.
  # - mean_conf: mean value of classifier confidence for true examples.
  # - std_conf: standard deviation of confidence for both true and false
  #             examples.
   - id: 1   # Must start at 1, 0 is reserved for generic background.
    activity_id: 1
    description: >-
      Not started.
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 2
    activity_id: 2
    description: >-
      Place tourniquet over affected extremity 2-3 inches above wound site (step 1).
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 3
    activity_id: 3
    description: >-
      In between steps 1 and 2.
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 4
    activity_id: 4
    description: >-
      Pull tourniquet tight (step 2).
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2

  - id: 5
    activity_id: 5
    description: >-
      In between steps 2 and 3.
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2

  - id: 6
    activity_id: 6
    description: >-
      Apply strap to strap body (step 3).
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
   
  - id: 7
    activity_id: 7
    description: >-
      In between steps 3 and 4.
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 8
    activity_id: 8
    description: >-
      Turn windless clock wise or counter clockwise until hemorrhage is controlled (step 4).
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 9
    activity_id: 9
    description: >-
      In between steps 4 and 5.
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 10
    activity_id: 10
    description: >-
      Lock windless into the windless keeper (step 5).
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 11
    activity_id: 11
    description: >-
      In between steps 5 and 6.
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 12
    activity_id: 12
    description: >-
      Pull remaining strap over the windless keeper (step 6).
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 13
    activity_id: 13
    description: >-
      In between steps 6 and 7.
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 14
    activity_id: 14
    description: >-
      Secure strap and windless keeper with keeper securing device (step 7).
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2

  - id: 15
    activity_id: 15
    description: >-
      In between steps 7 and 8.
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 16
    activity_id: 16
    description: >-
      Mark time on securing device strap with permanent marker (step 8).
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
    
  - id: 17
    activity_id: 17
    description: >-
      Finished.
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2

# Hidden markov model configuration parameters
hmm:
  # Time (seconds) between time steps of HMM. Sets the temporal precision of
  # the HMM analysis at the expense of processing costs.
  dt: 0.5

  # Constrain whether HMM sequence can skip steps or jump backwards. When both
  # values are set to 0, forward progress without skipping steps is enforced.
  num_steps_can_jump_fwd: 0
  num_steps_can_jump_bck: 0

  # Default classifier mean confidence to use if not explicitly provided for a
  # step.
  default_mean_conf: 0.5

  # Default classifier standard deviation of confidence to use if not
  # explicitly provided for a step.
  default_std_conf: 0.2
