# Schema version.
version: "1.0"

# Reference to the activity classification labels configuration that we will
# reference into.
activity_labels: "./config/activity_labels/recipe_m2_apply_tourniquet.yaml"

# Reference to the file defining the mean and standard deviation of the
# activity classifications to be used by the HMM. For N activities, both the
# mean and standard deviation should be N x N matrices such that when activity
# i is actually occuring, the classifier will emit confidence
# mean[i, j] +/- std[i, j] for activity j.
activity_mean_and_std_file: "./model_files/recipe_m2_apply_tourniquet.npy"

# Task title for display purposes.
title: "M2 Apply tourniquet"

# Layout of the steps that define this task.
steps:
  # Item format:
  # - id: Identifying integer for the step.
  # - activity_id: The ID of an activity classification associated with this
  #                step. This must reference an ID within the `activity_labels`
  #                configuration file referenced above.
  # - description: Human semantic description of this step.
  # - median_duration_seconds: Median expected time this task will
  #                            consume in seconds.
  # - mean_conf: mean value of classifier confidence for true examples.
  # - std_conf: standard deviation of confidence for both true and false
  #             examples.
  - id: 1   # Must start at 1, 0 is reserved for background.
    activity_id: 1
    description: >-
      Place tourniquet over affected extremity 2-3 inches above wound site
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
  - id: 2
    activity_id: 2
    description: >-
      Pull tourniquet tight
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
  - id: 3
    activity_id: 3
    description: >-
      Cinch tourniquet strap
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
  - id: 4
    activity_id: 4
    description: >-
      Apply strap to strap body
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
  - id: 5
    activity_id: 5
    description: >-
      Turn windless clock wise or counter clockwise until hemorrhage is controlled
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
  - id: 6
    activity_id: 6
    description: >-
      Lock windless into the windless keeper
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
  - id: 7
    activity_id: 7
    description: >-
      Pull remaining strap over the windless keeper
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
  - id: 8
    activity_id: 8
    description: >-
      Secure strap and windless keeper with keeper securing device
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2
  - id: 9
    activity_id: 9
    description: >-
      Mark time on securing device strap with permanent marker
    median_duration_seconds: 5
    mean_conf: 0.5
    std_conf: 0.2

# Hidden markov model configuration parameters
hmm:
  # Time (seconds) between time steps of HMM. Sets the temporal precision of
  # the HMM analysis at the expense of processing costs.
  dt: 0.5

  # Constrain whether HMM sequence can skip steps or jump backwards. When both
  # values are set to 0, forward progress without skipping steps is enforced.
  num_steps_can_jump_fwd: 1
  num_steps_can_jump_bck: 0

  # Default classifier mean confidence to use if not explicitly provided for a
  # step.
  default_mean_conf: 0.5

  # Default classifier standard deviation of confidence to use if not
  # explicitly provided for a step.
  default_std_conf: 0.2
