version: "1.1"
title: "All Recipes"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "hand (left)"
  - id: 2
    label: "hand (right)"
  - id: 3
    label: "paper towel"
  - id: 4
    label: "paper towel sheet"
  - id: 5
    label: "water jug lid"
  - id: 6
    label: "water jug (open)"
  - id: 7
    label: "water jug (closed)"
  - id: 8
    label: "cutting board"
  - id: 9
    label: "butter knife"
  - id: 10
    label: "banana"
  - id: 11
    label: "banana (peeled)"
  - id: 12
    label: "sliced banana"
  - id: 13
    label: "cinnamon (open)"
  - id: 14
    label: "cinnamon (closed)"
  - id: 15
    label: "tortilla"
  - id: 16
    label: "tortilla bag"
  - id: 17
    label: "plate (empty)"
  - id: 18
    label: "kettle lid"
  - id: 19
    label: "kettle (open)"
  - id: 20
    label: "kettle (closed)"
  - id: 21
    label: "spoon"
  - id: 22
    label: "jar of honey (open)"
  - id: 23
    label: "jar of honey (closed)"
  - id: 24
    label: "measuring cup"
  - id: 25
    label: "container"
  - id: 26
    label: "mug"
  - id: 27
    label: "kettle switch"
  - id: 28
    label: "thermometer (open)"
  - id: 29
    label: "thermometer (closed)"
  - id: 30
    label: "timer (on)"
  - id: 31
    label: "timer (off)"
  - id: 32
    label: "trash can"
  # Labels unique to coffee
  - id: 33
    label: "coffee + mug"
  - id: 34
    label: "coffee bag"
  - id: 35
    label: "coffee beans + container"
  - id: 36
    label: "coffee beans + container + scale"
  - id: 37
    label: "coffee grounds + paper filter (quarter - open) + dripper"
  - id: 38
    label: "coffee grounds + paper filter (quarter - open) + dripper + mug"
  - id: 39
    label: "container + scale"
  - id: 40
    label: "dripper" # previously filter cone
  - id: 41
    label: "dripper + mug"
  - id: 42
    label: "grinder lid"
  - id: 43
    label: "grinder (open)"
  - id: 44
    label: "grinder (closed)"
  - id: 45
    label: "paper filter"
  - id: 46
    label: "paper filter (semi)"
  - id: 47
    label: "paper filter (quarter)"
  - id: 48
    label: "used paper filter (quarter) + dripper"
  - id: 49
    label: "paper filter (quarter) + dripper"
  - id: 50
    label: "paper filter (quarter) + dripper + mug"
  - id: 51
    label: "paper filter (quarter - open) + dripper"
  - id: 52
    label: "paper filter (quarter - open) + dripper + mug"
  - id: 53
    label: "paper filter bag"
  - id: 54
    label: "stack of paper filters"
  - id: 55
    label: "scale (on)"
  - id: 56
    label: "scale (off)"
  - id: 57
    label: "used paper filter" # out of the mug completely
  - id: 58
    label: "used paper filter (quarter - open) + dripper"
  - id: 59
    label: "used paper filter (quarter - open) + dripper + mug"
  - id: 121
    label: "used paper filter (quarter) + dripper + mug"
  # Labels unique to dessert quesadilla
  - id: 60
    label: "nutella jar lid"
  - id: 61
    label: "nutella jar (open)"
  - id: 62
    label: "nutella jar (closed)"
  - id: 63
    label: "butter knife + nutella"
  - id: 64
    label: "tortilla + nutella"
  - id: 65
    label: "tortilla + cinnamon"
  - id: 66
    label: "tortilla + nutella + sliced banana"
  - id: 67
    label: "tortilla + nutella + cinnamon"
  - id: 68
    label: "tortilla + nutella + sliced banana + cinnamon"
  - id: 69
    label: "folded tortilla (semi)"
  - id: 70
    label: "tortilla wedge"
  - id: 71
    label: "plate + tortilla wedge(s)"
  # Labels unique to oatmeal
  - id: 72
    label: "tablespoon"
  - id: 73
    label: "tablespoon + oats"
  - id: 74
    label: "bowl"
  - id: 75
    label: "microwave (open)"
  - id: 76
    label: "microwave (closed)"
  - id: 77
    label: "container of oats lid"
  - id: 78
    label: "container of oats (open)"
  - id: 79
    label: "container of oats (closed)"
  - id: 80
    label: "box of raisins"
  - id: 81
    label: "raisins"
  - id: 82
    label: "container + raisins"
  - id: 83
    label: "bowl + oats"
  - id: 84
    label: "bowl + water"
  - id: 85
    label: "bowl + oats + water"
  - id: 86
    label: "bowl + oats + water + raisins"
  - id: 87
    label: "oatmeal" # "bowl + oats + water + raisins (stirred)"
  - id: 88
    label: "oatmeal + sliced banana"
  - id: 89
    label: "oatmeal + cinnamon"
  - id: 90
    label: "oatmeal + honey"
  - id: 91
    label: "oatmeal + sliced banana + cinnamon"
  - id: 92
    label: "oatmeal + sliced banana + honey"
  - id: 93
    label: "oatmeal + sliced banana + cinnamon + honey"
  # Labels unique to pinwheels
  - id: 94
    label: "nut butter jar lid"
  - id: 95
    label: "nut butter jar (open)"
  - id: 96
    label: "nut butter jar (closed)"
  - id: 97
    label: "jelly jar lid"
  - id: 98
    label: "jelly jar (open)"
  - id: 99
    label: "jelly jar (closed)"
  - id: 100
    label: "box of toothpicks (open)"
  - id: 101
    label: "container + box of toothpicks (open)"
  - id: 102
    label: "toothpick"
  - id: 103
    label: "box of dental floss (open)"
  - id: 104
    label: "box of dental floss (closed)"
  - id: 105
    label: "dental floss string"
  - id: 106
    label: "butter knife + nut butter"
  - id: 107
    label: "butter knife + jelly"
  - id: 108
    label: "tortilla + nut butter"
  - id: 109
    label: "tortilla + jelly"
  - id: 110
    label: "tortilla + nut butter + jelly"
  - id: 111
    label: "tortilla (rolled)"
  - id: 112
    label: "tortilla (rolled) + toothpick(s)"
  - id: 113
    label: "pinwheel + toothpick"
  - id: 114
    label: "plate + pinwheel(s) + toothpick"
  # Labels unique to tea
  - id: 115
    label: "tea bag (dry)"
  - id: 116
    label: "tea bag (wet)"
  - id: 117
    label: "mug + tea bag"
  - id: 118
    label: "mug + water"
  - id: 119
    label: "mug + tea bag + water"
  - id: 120
    label: "mug + tea"
  - id: 121
    label: "used paper filter (quarter) + dripper + mug"
