version: "2.1"
title: "Pinwheels"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "hand (left)"
  - id: 2
    label: "hand (right)"
  - id: 3
    label: "paper towel"
  - id: 4
    label: "paper towel sheet"
  - id: 8
    label: "cutting board"
  - id: 9
    label: "butter knife"
  - id: 15
    label: "tortilla"
  - id: 16
    label: "tortilla bag"
  - id: 17
    label: "plate (empty)"
  - id: 25
    label: "container" # prep bowl
  # Labels unique to pinwheels
  - id: 94
    label: "nut butter jar lid"
  - id: 95
    label: "nut butter jar (open)"
  - id: 96
    label: "nut butter jar (closed)"
  - id: 97
    label: "jelly jar lid"
  - id: 98
    label: "jelly jar (open)"
  - id: 99
    label: "jelly jar (closed)"
  - id: 100
    label: "box of toothpicks (open)"
  - id: 101
    label: "container + box of toothpicks (open)"
  - id: 102
    label: "toothpick"
  - id: 103
    label: "box of dental floss (open)"
  - id: 104
    label: "box of dental floss (closed)"
  - id: 105
    label: "dental floss string"
  - id: 106
    label: "butter knife + nut butter"
  - id: 107
    label: "butter knife + jelly"
  - id: 108
    label: "tortilla + nut butter"
  - id: 109
    label: "tortilla + jelly"
  - id: 110
    label: "tortilla + nut butter + jelly"
  - id: 111
    label: "tortilla (rolled)"
  - id: 112
    label: "tortilla (rolled) + toothpick(s)"
  - id: 113
    label: "pinwheel + toothpick"
  - id: 114
    label: "plate + pinwheel(s) + toothpick"
  - id: 123
    label: "tortilla (partially rolled)"
  - id: 124:
    label: "tortilla end"
